// apps/api/src/tests/checkout.contract.test.ts
// Contract regression test to prevent future API drift
// Generated by IBM Bob IDE - Task 3

import request from "supertest";
import express from "express";
import checkoutRouter from "../routes/checkout";

const app = express();
app.use(express.json());
app.use("/api", checkoutRouter);

describe("POST /api/checkout - Contract Test", () => {
  it("should return totalCents as integer (not total as float)", async () => {
    const response = await request(app)
      .post("/api/checkout")
      .send({ items: [{ id: "1", qty: 1 }] })
      .expect(200);

    // Assert: totalCents exists and is a number
    expect(response.body).toHaveProperty("totalCents");
    expect(typeof response.body.totalCents).toBe("number");
    expect(Number.isInteger(response.body.totalCents)).toBe(true);

    // Assert: total does NOT exist (old contract field)
    expect(response.body).not.toHaveProperty("total");
  });

  it('should return status in uppercase (e.g., "PAID" not "paid")', async () => {
    const response = await request(app)
      .post("/api/checkout")
      .send({ items: [{ id: "1", qty: 1 }] })
      .expect(200);

    // Assert: status exists and is uppercase
    expect(response.body).toHaveProperty("status");
    expect(typeof response.body.status).toBe("string");
    expect(response.body.status).toBe(response.body.status.toUpperCase());
  });

  it("should return all required fields with correct types", async () => {
    const response = await request(app)
      .post("/api/checkout")
      .send({ items: [{ id: "1", qty: 1 }] })
      .expect(200);

    // Assert: orderId exists and is a string
    expect(response.body).toHaveProperty("orderId");
    expect(typeof response.body.orderId).toBe("string");

    // Assert: totalCents is positive integer
    expect(response.body.totalCents).toBeGreaterThan(0);

    // Assert: status is valid enum value
    expect(["PENDING", "PAID", "FAILED"]).toContain(response.body.status);
  });
});

// Made with Bob
