"use client";
interface ContractTestPanelProps {
  onNext: () => void;
  onBack: () => void;
}
export default function ContractTestPanel({
  onNext,
  onBack,
}: ContractTestPanelProps) {
  const testCode = `// apps/api/src/tests/checkout.contract.test.ts
// Contract regression test to prevent future API drift
// Generated by IBM Bob IDE - Task 3

import request from "supertest";
import express from "express";
import checkoutRouter from "../routes/checkout";

describe("POST /api/checkout - Contract Test", () => {
  it("should return totalCents as integer (not total as float)", async () => {
    const response = await request(app)
      .post("/api/checkout")
      .send({ items: [{ id: "1", qty: 1 }] })
      .expect(200);

    // Assert: totalCents exists and is a number
    expect(response.body).toHaveProperty("totalCents");
    expect(typeof response.body.totalCents).toBe("number");
    expect(Number.isInteger(response.body.totalCents)).toBe(true);

    // Assert: total does NOT exist (old contract field)
    expect(response.body).not.toHaveProperty("total");
  });

  it('should return status in uppercase (e.g., "PAID" not "paid")', async () => {
    const response = await request(app)
      .post("/api/checkout")
      .send({ items: [{ id: "1", qty: 1 }] })
      .expect(200);

    // Assert: status exists and is uppercase
    expect(response.body).toHaveProperty("status");
    expect(response.body.status).toBe(response.body.status.toUpperCase());
  });

  it("should return all required fields with correct types", async () => {
    const response = await request(app)
      .post("/api/checkout")
      .send({ items: [{ id: "1", qty: 1 }] })
      .expect(200);

    expect(response.body.totalCents).toBeGreaterThan(0);
    expect(["PENDING", "PAID", "FAILED"]).toContain(response.body.status);
  });
});`;

  return (
    <div>
      <h1 className="text-3xl font-bold mb-2">Contract Test</h1>
      <p className="text-gray-600 mb-6">
        Regression test to prevent future drift
      </p>

      <div className="mb-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
        <p className="text-sm text-blue-900">
          <strong>🤖 Bob Generated:</strong> Contract regression test using Jest
          + Supertest
        </p>
      </div>

      <div className="bg-gray-900 text-gray-100 p-6 rounded-lg font-mono text-xs overflow-x-auto">
        <pre className="whitespace-pre-wrap">{testCode}</pre>
      </div>

      <div className="mt-6 p-4 bg-green-50 border border-green-200 rounded-lg">
        <p className="text-green-900">
          <strong>✅ Test Coverage:</strong> 3 test cases ensure{" "}
          <span className="font-mono">totalCents</span> exists as integer,
          <span className="font-mono">total</span> does NOT exist, and{" "}
          <span className="font-mono">status</span> is uppercase.
        </p>
      </div>

      <div className="mt-4 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
        <p className="text-sm text-yellow-900">
          <strong>🎯 Purpose:</strong> This test will{" "}
          <span className="font-bold text-red-600">FAIL</span> if the API drifts
          back to the old contract, preventing future regressions.
        </p>
      </div>

      <div className="flex justify-between mt-8">
        <button
          onClick={onBack}
          className="px-6 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition"
        >
          ← Back
        </button>
        <button
          onClick={onNext}
          className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
        >
          Next: Ticket Routing →
        </button>
      </div>
    </div>
  );
}

// Made with Bob
